### ISSUE TITLE
ReferenceError: Bmob is not defined

### ISSUE THREAD

**Issue by SaulJWu** [zpfz/Vilike.js#2]
```
ReferenceError: Bmob is not defined
    at Object.e.init (node_modules/vilike/dist/ViLike.min.js:1:682)
    at Module.<anonymous> (docs/.vuepress/enhanceApp.js:24:7)
    at __webpack_require__ (webpack/bootstrap:25:0)
    at Object.<anonymous> (server-bundle.js:9215:18)
    at __webpack_require__ (webpack/bootstrap:25:0)
    at server-bundle.js:118:18
    at Object.<anonymous> (server-bundle.js:121:10)
    at evaluateModule (C:\Projects\SaulJWu.github.io\node_modules\vue-server-renderer\build.dev.js:9318:21)
    at C:\Projects\SaulJWu.github.io\node_modules\vue-server-renderer\build.dev.js:9376:18
    at new Promise (<anonymous>)
    at C:\Projects\SaulJWu.github.io\node_modules\vue-server-renderer\build.dev.js:9368:14
    at Object.renderToString (C:\Projects\SaulJWu.github.io\node_modules\vue-server-renderer\build.dev.js:9544:9)       
    at Build.renderPage (C:\Projects\SaulJWu.github.io\node_modules\@vuepress\core\lib\node\build\index.js:150:34)      
    at C:\Projects\SaulJWu.github.io\node_modules\@vuepress\core\lib\node\build\index.js:95:43
    at Array.map (<anonymous>)
    at Build.render (C:\Projects\SaulJWu.github.io\node_modules\@vuepress\core\lib\node\build\index.js:95:26)
```

在vuepress部署时，打包不上去了，本地localhost测试没有问题
package.json
```json
{
  "name": "theme-vdoing-blog",
  "version": "1.0.0",
  "scripts": {
    "push": "bash pushCode.sh",
    "dev": "vuepress dev docs",
    "build": "vuepress build docs docs && node utils/googlePush.js https://sauljwu.github.io/",
    "deploy": "bash deploy.sh",
    "editFm": "node utils/editFrontmatter.js",
    "baiduPush": "node utils/baiduPush.js https://sauljwu.github.io/ && bash baiduPush.sh",
    "googlePush": "node utils/googlePush.js https://sauljwu.github.io/ && bash googlePush.sh",
    "publish": "cd theme-vdoing && npm publish && cd ../ && npm update vuepress-theme-vdoing",
    "updateTheme": "npm uninstall vuepress-theme-vdoing && rm -rf node_modules && npm i && npm i vuepress-theme-vdoing -D"
  },
  "license": "MIT",
  "devDependencies": {
    "inquirer": "^7.3.3",
    "json2yaml": "^1.1.0",
    "moment": "^2.29.1",
    "vuepress": "1.8.0",
    "vuepress-plugin-baidu-autopush": "^1.0.1",
    "vuepress-plugin-baidu-tongji": "^1.0.1",
    "vuepress-plugin-demo-block": "^0.7.2",
    "vuepress-plugin-one-click-copy": "^1.0.2",
    "vuepress-plugin-thirdparty-search": "^1.0.2",
    "vuepress-plugin-zooming": "^1.1.8",
    "vuepress-theme-vdoing": "^1.8.1",
    "yamljs": "^0.3.0"
  },
  "dependencies": {
    "busuanzi.pure.js": "^1.0.3",
    "vilike": "^0.1.2",
    "vuepress-plugin-comment": "^0.7.3",
    "vuepress-plugin-sitemap": "^2.3.1"
  }
}

```

**Comment by SaulJWu** [comment]
在我参考https://github.com/vuejs/vuepress/issues/2651
之后，
```
import ViLike from 'vilike'
import Bmob from "hydrogen-js-sdk";

export default ({
  Vue,
  options,
  router,
  siteData,
}) => {
    Vue.use(Bmob);
  Vue.use(ViLike);
}

// 请自行修改相关配置信息
ViLike.configure({
  secretKey: 'xxx',
  safeKey: 'xxx',
  table: 'xxx',
  key: 'xxx',
  visit: 'xxx',
  like: 'xxx'
});
// 初始化
ViLike.init();
```

又出现了

```
Error in created hook: "ReferenceError: ViLike is not defined"

found in

---> <Buttons>
       <Anonymous>
         <GlobalLayout>
           <Root>
error Error rendering /pages/c3d3a0/: false
undefined
error Error rendering /categories/: false
undefined
error Error rendering /archives/: false
undefined
error Error rendering /friends/: false
undefined
error Error rendering /tags/: false
undefined
```

**Comment by SaulJWu** [comment]
` Vue.use(Bmob).use(ViLike);`
也不行啊，有人知道为什么么

**Comment by zpfz** [comment]
请参考文档：https://vilike.vercel.app/docs/vuepress  
很急的话建议加QQ群即时交流：867711329
